-- MySQL Script generated by MySQL Workbench
-- Sun 27 Mar 2016 12:51:41 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apiculture
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apiculture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apiculture` DEFAULT CHARACTER SET utf8 ;
USE `apiculture` ;

-- -----------------------------------------------------
-- Table `apiculture`.`activitecolonie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`activitecolonie` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`adresse` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numCivique` INT(11) NOT NULL,
  `nomRue` VARCHAR(100) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `codePostal` VARCHAR(10) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  `nomEmplacement` VARCHAR(100) NULL DEFAULT NULL,
  `numLot` INT(11) NULL DEFAULT NULL,
  `longitude` VARCHAR(100) NULL DEFAULT NULL,
  `latitude` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apiculture`.`expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`expertise` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`personne` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `idAdresse` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `personne_adresse_idx` (`idAdresse` ASC),
  CONSTRAINT `personne_adresse`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `apiculture`.`adresse` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`employe` (
  `idPersonne` INT(11) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `idExpertise` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersonne`),
  INDEX `employe_expertise_idx` (`idExpertise` ASC),
  CONSTRAINT `employe_expertise`
    FOREIGN KEY (`idExpertise`)
    REFERENCES `apiculture`.`expertise` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `employe_personne`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`personne` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`rucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`rucher` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idAdresse` INT(11) NULL DEFAULT NULL,
  `idApiculteurPropiétaire` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `adresse_rucer_idx` (`idAdresse` ASC),
  CONSTRAINT `adresse_rucer`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `apiculture`.`adresse` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`apiculteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`apiculteur` (
  `idEmploye` INT(11) NOT NULL,
  `rucher_id` INT(11) NOT NULL,
  PRIMARY KEY (`idEmploye`, `rucher_id`),
  INDEX `fk_apiculteur_rucher1_idx` (`rucher_id` ASC),
  CONSTRAINT `apiculteur_employe`
    FOREIGN KEY (`idEmploye`)
    REFERENCES `apiculture`.`employe` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_apiculteur_rucher1`
    FOREIGN KEY (`rucher_id`)
    REFERENCES `apiculture`.`rucher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`typeelement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`typeelement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`fournisseur` (
  `idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`idPersonne`),
  CONSTRAINT `fournisseur_personne`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`personne` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`produit` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`fournisseurproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`fournisseurproduit` (
  `id` INT(11) NOT NULL,
  `idPersonne` INT(11) NOT NULL,
  `idProduit` INT(11) NOT NULL,
  `prixDetail` DECIMAL(2,2) NOT NULL,
  `prixGros` DECIMAL(2,2) NOT NULL,
  `quantiteMin` INT(11) NOT NULL,
  `quantiteDisponible` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Fournisseur_has_Produit_Produit1_idx` (`idProduit` ASC),
  INDEX `fk_Fournisseur_has_Produit_Fournisseur1_idx` (`idPersonne` ASC),
  CONSTRAINT `fk_Fournisseur_has_Produit_Fournisseur1`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`fournisseur` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Fournisseur_has_Produit_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `apiculture`.`produit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`element` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idType` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `dateFabrication` DATE NOT NULL,
  `dateAchat` DATE NOT NULL,
  `idFournisseurProduit` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_element_idx` (`idType` ASC),
  INDEX `element_fournisseurproduit_idx` (`idFournisseurProduit` ASC),
  CONSTRAINT `element_type`
    FOREIGN KEY (`idType`)
    REFERENCES `apiculture`.`typeelement` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `element_fournisseurproduit`
    FOREIGN KEY (`idFournisseurProduit`)
    REFERENCES `apiculture`.`fournisseurproduit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`cadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`cadre` (
  `idElement` INT(11) NOT NULL AUTO_INCREMENT,
  `plastique` TINYINT(1) NOT NULL DEFAULT '0',
  `cire` TINYINT(1) NOT NULL DEFAULT '0',
  `batis` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idElement`),
  CONSTRAINT `cadre_element`
    FOREIGN KEY (`idElement`)
    REFERENCES `apiculture`.`element` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`hausse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`hausse` (
  `idElement` INT(11) NOT NULL,
  `nbrCadres` INT(11) NOT NULL,
  `nbrCadresBatis` INT(11) NOT NULL,
  `nbrCadresCirePlstique` INT(11) NOT NULL,
  `nbrCadresCireNaturelle` INT(11) NOT NULL,
  PRIMARY KEY (`idElement`),
  CONSTRAINT `hausse_element`
    FOREIGN KEY (`idElement`)
    REFERENCES `apiculture`.`element` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`cadrehausse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`cadrehausse` (
  `idCadre` INT(11) NOT NULL,
  `idHausse` INT(11) NOT NULL,
  `datePose` DATETIME NOT NULL,
  `dateRetrait` DATETIME NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCadre`, `idHausse`, `datePose`),
  INDEX `cadre_hausse_idx` (`idHausse` ASC),
  CONSTRAINT `cadre_hausse`
    FOREIGN KEY (`idHausse`)
    REFERENCES `apiculture`.`hausse` (`idElement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cadre_cadre`
    FOREIGN KEY (`idCadre`)
    REFERENCES `apiculture`.`cadre` (`idElement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apiculture`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`client` (
  `idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`idPersonne`),
  CONSTRAINT `employe_personne00`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`personne` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`racereine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`racereine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `couleur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`marquagereine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`marquagereine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `couleur` VARCHAR(100) NOT NULL,
  `remarque` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`tendanceessaimage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`tendanceessaimage` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tendance` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`reine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`reine` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anneeNaissance` DATE NOT NULL,
  `idRace` INT(11) NOT NULL,
  `estBridee` TINYINT(1) NOT NULL DEFAULT '0',
  `idMarquage` INT(11) NULL DEFAULT NULL,
  `idTendanceEssaimage` INT(11) NULL DEFAULT NULL,
  `idFournisseur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `race_reine_idx` (`idRace` ASC),
  INDEX `marquage_reine_idx` (`idMarquage` ASC),
  INDEX `tendance_essaimage_reine_idx` (`idTendanceEssaimage` ASC),
  CONSTRAINT `race_reine`
    FOREIGN KEY (`idRace`)
    REFERENCES `apiculture`.`racereine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `marquage_reine`
    FOREIGN KEY (`idMarquage`)
    REFERENCES `apiculture`.`marquagereine` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tendance_essaimage_reine`
    FOREIGN KEY (`idTendanceEssaimage`)
    REFERENCES `apiculture`.`tendanceessaimage` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`ruche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`ruche` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idRucher` INT(11) NOT NULL,
  `idReine` INT(11) NULL DEFAULT NULL,
  `directionRuche` VARCHAR(10) NOT NULL,
  `dateInstallation` DATETIME NOT NULL,
  `estActive` TINYINT(1) NOT NULL DEFAULT '0',
  `estDeTypeDadant` TINYINT(1) NOT NULL DEFAULT '0',
  `datePrelevementEssaim` DATETIME NOT NULL,
  `estUnEssaimNaturel` TINYINT(1) NOT NULL DEFAULT '0',
  `idRucheProvenanceEssaim` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rucher_provenance_idx` (`idRucheProvenanceEssaim` ASC),
  INDEX `ruche_rucher_idx` (`idRucher` ASC),
  INDEX `ruche_reine_idx` (`idReine` ASC),
  CONSTRAINT `rucher_provenance`
    FOREIGN KEY (`idRucheProvenanceEssaim`)
    REFERENCES `apiculture`.`ruche` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ruche_rucher`
    FOREIGN KEY (`idRucher`)
    REFERENCES `apiculture`.`rucher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ruche_reine`
    FOREIGN KEY (`idReine`)
    REFERENCES `apiculture`.`reine` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`coloniedisparue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`coloniedisparue` (
  `idRuche` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `cause` TEXT NOT NULL,
  PRIMARY KEY (`idRuche`),
  CONSTRAINT `coloniedisparue_ruche`
    FOREIGN KEY (`idRuche`)
    REFERENCES `apiculture`.`ruche` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`commande` (
  `id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `idClient` INT(11) NOT NULL,
  `idFournisseurProduit` INT(11) NOT NULL,
  `quantite` INT(11) NOT NULL,
  `total` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `commande_client_idx` (`idClient` ASC),
  INDEX `commande_fourniseurproduit_idx` (`idFournisseurProduit` ASC),
  CONSTRAINT `commande_client`
    FOREIGN KEY (`idClient`)
    REFERENCES `apiculture`.`client` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `commande_fourniseurproduit`
    FOREIGN KEY (`idFournisseurProduit`)
    REFERENCES `apiculture`.`fournisseurproduit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`conditionsmeteorologiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`conditionsmeteorologiques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `temperature` DECIMAL(2,2) NULL DEFAULT NULL,
  `humidite` DECIMAL(2,2) NULL DEFAULT NULL,
  `vent` DECIMAL(2,2) NULL DEFAULT NULL,
  `ilPleut` TINYINT(1) NULL DEFAULT NULL,
  `ilNeige` TINYINT(1) NULL DEFAULT NULL,
  `cielCouvert` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`courriel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`courriel` (
  `id` INT(11) NOT NULL,
  `courriel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`etatproduction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`etatproduction` (
  `id` INT(11) NOT NULL,
  `quantiteMiel` DECIMAL(2,2) NOT NULL,
  `quanitePollen` DECIMAL(2,2) NOT NULL,
  `mielPreleve` DECIMAL(2,2) NULL DEFAULT '0',
  `pollenPreleve` DECIMAL(2,2) NULL DEFAULT '0',
  `idProduit` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `etatproduction_produit_idx` (`idProduit` ASC),
  CONSTRAINT `etatproduction_produit`
    FOREIGN KEY (`idProduit`)
    REFERENCES `apiculture`.`produit` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apiculture`.`forcecolonie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`forcecolonie` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`qualitecouvain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`qualitecouvain` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`infection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`infection` (
  `id` INT(11) NOT NULL,
  `severite` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`etatcolonie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`etatcolonie` (
  `id` INT(11) NOT NULL,
  `idEtatProduction` INT(11) NULL DEFAULT NULL,
  `idForceColonie` INT(11) NULL DEFAULT NULL,
  `idQualiteCouvain` INT(11) NULL DEFAULT NULL,
  `nbreCadresCouvain` INT(11) NOT NULL,
  `reinePresente` TINYINT(1) NOT NULL,
  `fauxBourdonsPresents` TINYINT(1) NOT NULL,
  `oeufsMoinsDeQuatreJours` TINYINT(1) NOT NULL,
  `cellulesOpercules` TINYINT(1) NOT NULL,
  `temperamentColonie` DECIMAL(2,2) NOT NULL,
  `cellulesRoyales` TINYINT(1) NOT NULL,
  `idInfection` INT(11) NULL DEFAULT NULL,
  `idActivite` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `visite_etatproduction_idx` (`idEtatProduction` ASC),
  INDEX `visite_etat_force_coloonie_idx` (`idForceColonie` ASC),
  INDEX `visite_qualite_couvain_idx` (`idQualiteCouvain` ASC),
  INDEX `visite_infection_idx` (`idInfection` ASC),
  INDEX `visite_activite_idx` (`idActivite` ASC),
  CONSTRAINT `visite_etatproduction`
    FOREIGN KEY (`idEtatProduction`)
    REFERENCES `apiculture`.`etatproduction` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visite_etat_force_coloonie`
    FOREIGN KEY (`idForceColonie`)
    REFERENCES `apiculture`.`forcecolonie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visite_qualite_couvain`
    FOREIGN KEY (`idQualiteCouvain`)
    REFERENCES `apiculture`.`qualitecouvain` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visite_infection`
    FOREIGN KEY (`idInfection`)
    REFERENCES `apiculture`.`infection` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visite_activite`
    FOREIGN KEY (`idActivite`)
    REFERENCES `apiculture`.`activitecolonie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`isolation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`isolation` (
  `idElement` INT(11) NOT NULL,
  `doubleBullesAlum` TINYINT(1) NOT NULL,
  `polysterene` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idElement`),
  CONSTRAINT `element`
    FOREIGN KEY (`idElement`)
    REFERENCES `apiculture`.`element` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apiculture`.`visiterucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`visiterucher` (
  `id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `idConditionsMeteorologiques` INT(11) NULL DEFAULT NULL,
  `idRucher` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `visite_conditions_meteorologiques_idx` (`idConditionsMeteorologiques` ASC),
  INDEX `visite_rucher_idx` (`idRucher` ASC),
  CONSTRAINT `visite_conditions_meteorologiques`
    FOREIGN KEY (`idConditionsMeteorologiques`)
    REFERENCES `apiculture`.`conditionsmeteorologiques` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visite_rucher`
    FOREIGN KEY (`idRucher`)
    REFERENCES `apiculture`.`rucher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`visiteruche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`visiteruche` (
  `id` INT(11) NOT NULL,
  `idVisite` INT(11) NOT NULL,
  `idRuche` INT(11) NOT NULL,
  `idEmploye` INT(11) NULL DEFAULT NULL,
  `heure` TIME NOT NULL,
  `idEtatColonie` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `visiteruche_visite_idx` (`idVisite` ASC),
  INDEX `visiteruche_ruche_idx` (`idRuche` ASC),
  INDEX `visiteruche_employe_idx` (`idEmploye` ASC),
  INDEX `visiteruche_etatcolonie_idx` (`idEtatColonie` ASC),
  CONSTRAINT `visiteruche_visite`
    FOREIGN KEY (`idVisite`)
    REFERENCES `apiculture`.`visiterucher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `visiteruche_ruche`
    FOREIGN KEY (`idRuche`)
    REFERENCES `apiculture`.`ruche` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `visiteruche_employe`
    FOREIGN KEY (`idEmploye`)
    REFERENCES `apiculture`.`employe` (`idPersonne`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `visiteruche_etatcolonie`
    FOREIGN KEY (`idEtatColonie`)
    REFERENCES `apiculture`.`etatcolonie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`media` (
  `id` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `donnees` BINARY(1) NOT NULL,
  `extension` VARCHAR(5) NOT NULL,
  `idVisiteRuche` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `media_visiteruche_idx` (`idVisiteRuche` ASC),
  CONSTRAINT `media_visiteruche`
    FOREIGN KEY (`idVisiteRuche`)
    REFERENCES `apiculture`.`visiteruche` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`medicament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`medicament` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`personnecourriel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`personnecourriel` (
  `idPersonne` INT(11) NOT NULL,
  `idCourriel` INT(11) NOT NULL,
  PRIMARY KEY (`idPersonne`, `idCourriel`),
  INDEX `fk_Employe_has_Courriel_Courriel1_idx` (`idCourriel` ASC),
  CONSTRAINT `personnecourriel_personne`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`personne` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personnecourriel_courriel`
    FOREIGN KEY (`idCourriel`)
    REFERENCES `apiculture`.`courriel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`telephone` (
  `id` INT(11) NOT NULL,
  `telephone` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`personnetelephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`personnetelephone` (
  `idPersonne` INT(11) NOT NULL,
  `idTelephone` INT(11) NOT NULL,
  PRIMARY KEY (`idPersonne`, `idTelephone`),
  INDEX `fk_Employe_has_Telephone_Telephone1_idx` (`idTelephone` ASC),
  CONSTRAINT `personnetelephone_personne`
    FOREIGN KEY (`idPersonne`)
    REFERENCES `apiculture`.`personne` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personnetelephone_telephone`
    FOREIGN KEY (`idTelephone`)
    REFERENCES `apiculture`.`telephone` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`qualitedefaut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`qualitedefaut` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estUneQualite` TINYINT(1) NOT NULL DEFAULT '1',
  `desciption` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`qualitedefautreine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`qualitedefautreine` (
  `idQualiteDefaut` INT(11) NOT NULL,
  `idReine` INT(11) NOT NULL,
  PRIMARY KEY (`idQualiteDefaut`, `idReine`),
  INDEX `qualite_defaut_reine_idx` (`idReine` ASC),
  CONSTRAINT `qualite_defaut_reine`
    FOREIGN KEY (`idReine`)
    REFERENCES `apiculture`.`reine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reine_qualite_defaut`
    FOREIGN KEY (`idQualiteDefaut`)
    REFERENCES `apiculture`.`qualitedefaut` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`recommandationtraitement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`recommandationtraitement` (
  `id` INT(11) NOT NULL,
  `idInfection` INT(11) NOT NULL,
  `idMedicament` INT(11) NOT NULL,
  `quantite` DECIMAL(2,2) NOT NULL,
  `dosage` VARCHAR(100) NOT NULL,
  `frequence` VARCHAR(100) NOT NULL,
  `dateDebutSuggere` DATE NULL DEFAULT NULL,
  `dateFinMax` DATE NULL DEFAULT NULL,
  `observation` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `signeexterne_infection_idx` (`idInfection` ASC),
  INDEX `traitement_medicament_idx` (`idMedicament` ASC),
  CONSTRAINT `recommandation_traitement`
    FOREIGN KEY (`idInfection`)
    REFERENCES `apiculture`.`infection` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `traitement_medicament`
    FOREIGN KEY (`idMedicament`)
    REFERENCES `apiculture`.`medicament` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`signeexterneinfection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`signeexterneinfection` (
  `id` INT(11) NOT NULL,
  `signe` VARCHAR(100) NOT NULL,
  `idInfection` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `signeexterne_infection_idx` (`idInfection` ASC),
  CONSTRAINT `signeexterne_infection`
    FOREIGN KEY (`idInfection`)
    REFERENCES `apiculture`.`infection` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`traitement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`traitement` (
  `id` INT(11) NOT NULL,
  `idInfection` INT(11) NOT NULL,
  `idRecomandation` INT(11) NULL DEFAULT NULL,
  `idMedicament` INT(11) NOT NULL,
  `quantite` DECIMAL(2,2) NOT NULL,
  `dosage` VARCHAR(100) NOT NULL,
  `frequence` VARCHAR(100) NOT NULL,
  `dateDebutEffective` DATE NOT NULL,
  `idEmploye` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `signeexterne_infection_idx` (`idInfection` ASC),
  INDEX `traitement_medicament_idx` (`idMedicament` ASC),
  INDEX `traitement_employe_idx` (`idEmploye` ASC),
  INDEX `traitement_recommandation_idx` (`idRecomandation` ASC),
  CONSTRAINT `recommandation_traitement0`
    FOREIGN KEY (`idInfection`)
    REFERENCES `apiculture`.`infection` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `traitement_medicament0`
    FOREIGN KEY (`idMedicament`)
    REFERENCES `apiculture`.`medicament` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `traitement_employe0`
    FOREIGN KEY (`idEmploye`)
    REFERENCES `apiculture`.`employe` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `traitement_recommandation`
    FOREIGN KEY (`idRecomandation`)
    REFERENCES `apiculture`.`recommandationtraitement` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apiculture`.`PoseElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apiculture`.`PoseElement` (
  `ruche_id` INT(11) NOT NULL,
  `element_id` INT(11) NOT NULL,
  `date_pose` DATETIME NOT NULL,
  `date_retrait` DATETIME NOT NULL COMMENT 'un cadre meme si c\'est un element, sa pose est geree par la table cadrehausse',
  PRIMARY KEY (`ruche_id`, `element_id`),
  INDEX `fk_ruche_has_element_element1_idx` (`element_id` ASC),
  INDEX `fk_ruche_has_element_ruche1_idx` (`ruche_id` ASC),
  CONSTRAINT `fk_ruche_has_element_ruche1`
    FOREIGN KEY (`ruche_id`)
    REFERENCES `apiculture`.`ruche` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruche_has_element_element1`
    FOREIGN KEY (`element_id`)
    REFERENCES `apiculture`.`element` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
